/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMentoriasRouteImport } from './routes/app.mentorias'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBuscarRouteImport } from './routes/app.buscar'
import { Route as AppMentorIdRouteImport } from './routes/app.mentor.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMentoriasRoute = AppMentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorIdRoute = AppMentorIdRouteImport.update({
  id: '/mentor/$id',
  path: '/mentor/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/mentorias': typeof AppMentoriasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/mentor/$id': typeof AppMentorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/mentorias': typeof AppMentoriasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/mentor/$id': typeof AppMentorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/chat': typeof AppChatRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/mentorias': typeof AppMentoriasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/mentor/$id': typeof AppMentorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/buscar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/mentorias'
    | '/app/perfil'
    | '/app/mentor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/buscar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/mentorias'
    | '/app/perfil'
    | '/app/mentor/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/buscar'
    | '/app/chat'
    | '/app/dashboard'
    | '/app/mentorias'
    | '/app/perfil'
    | '/app/mentor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentorias': {
      id: '/app/mentorias'
      path: '/mentorias'
      fullPath: '/app/mentorias'
      preLoaderRoute: typeof AppMentoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buscar': {
      id: '/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentor/$id': {
      id: '/app/mentor/$id'
      path: '/mentor/$id'
      fullPath: '/app/mentor/$id'
      preLoaderRoute: typeof AppMentorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMentoriasRoute: typeof AppMentoriasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppMentorIdRoute: typeof AppMentorIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMentoriasRoute: AppMentoriasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppMentorIdRoute: AppMentorIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
